name: bookinghotel
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  hive_flutter: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  smooth_page_indicator: ^1.0.1
  syncfusion_flutter_datepicker: ^21.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
